# Generated by Django 6.0.4 on 2026-04-22 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('success', 'Success'), ('warning', 'Warning'), ('normal', 'Normal')], default='normal', max_length=25)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chats_notemodel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(db_index=True, help_text='OneSignal player ID from mobile/web SDK', max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], default='android', help_text='Device operating system', max_length=20)),
                ('device_token', models.CharField(blank=True, help_text='FCM token or APNS token for backup', max_length=500)),
                ('device_name', models.CharField(blank=True, help_text='Device model or name (optional, for tracking)', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether device is eligible for push notifications')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Last time device registered or refreshed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Last login device for this user', on_delete=django.db.models.deletion.CASCADE, related_name='notification_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['-last_activity'],
                'constraints': [models.UniqueConstraint(fields=('user',), name='unique_active_device_per_user')],
            },
        ),
    ]
